💚 Yaay, debugging github action!

diff --git a/.github/workflows/requestservice.yml b/.github/workflows/requestservice.yml
--- a/.github/workflows/requestservice.yml
+++ b/.github/workflows/requestservice.yml
@@ -32,7 +32,11 @@ jobs:
           image: maven:3.9.9-eclipse-temurin-21
           options: -v ${{ github.workspace }}:/workspace -w /workspace
           run: |
-            cd requestservice && mvn -B clean package
+            run: |
+              pwd
+              ls -la
+              ls -la requestservice || echo "requestservice not found"
+
             
       - name: Build Docker image
         run: |
